<form action="<?php echo $this->getUrl("employee/save/index")?>" method="post">
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" class="form-control" name="name" id="name">
  </div>
  <div class="form-group">
    <label for="division">division:</label>
    <input type="text" class="form-control" name="division" id="division">
  </div>
  <button type="submit" class="btn btn-default">Add</button>
</form>